export { Chat } from './components/chat.js';
export type {
  ChatConfirmationAction,
  ChatConfirmationChangeDetail,
  ChatConfirmationRequest,
  ChatConfirmationResolvedRequest,
  ChatConfirmationResult,
  ChatConfirmationVariant,
} from './components/chat.js';
export { registerRenderer } from './register-renderer.js';
export { registerPartRenderer } from './register-part-renderer.js';

// Re-export commonly used types and utilities so consumers don't need
// to install the sub-packages separately.
export type {
  ChatMessage,
  ChatMessageRole,
  ChatConfig,
  BlockRenderer,
  PartRenderer,
  DateSeparatorLabels,
  ChatFormSubmitDetail,
  ChatFormFieldValues,
  ChatFormDateRangeValue,
  ChatPartActionDetail,
  ChatPartActionKind,
  MessagePart,
  PartBase,
  PartStatus,
  BuiltInMessagePartType,
  TaskStatus,
  TextPart,
  ReasoningPart,
  ToolCallPart,
  ToolCallState,
  FilePart,
  SourcePart,
  TodoItemStatus,
  TodoItem,
  TodoItemPatch,
  TodoPart,
  TodoPartOptions,
  TodoActionDetail,
  ToolActionDetail,
  CustomPart,
  PartFactoryOptions,
  ChatLabels,
  ComposerLabels,
  ReasoningLabels,
  ToolCallLabels,
  TodoLabels,
  MessagesLabels,
  ConfirmationLabels,
  DeepPartial,
  PluralForms,
  ChatLinkClickDetail,
  MarkdownRenderOptions,
} from '@bndynet/ichat-messages';
export {
  DEFAULT_CONFIG,
  BUILT_IN_MESSAGE_PART_TYPES,
  getMessageText,
  isBuiltInMessagePartType,
  isCustomMessagePartType,
  textPart,
  reasoningPart,
  todoPart,
  nextPartId,
  areTodoItemsTerminal,
  isTerminalTodoItem,
  patchTodoItemInPart,
  getTodoInitialExpanded,
  shouldInitializeTodoExpansion,
  createFormSubmitDetail,
  createPartActionDetail,
  createTodoActionDetail,
  createToolActionDetail,
  rendererRegistry,
  partRendererRegistry,
  StreamingController,
  resolveDateSeparatorLabels,
  makeDaysAgo,
  DATE_SEPARATOR_LABELS_EN,
  DATE_SEPARATOR_LABELS_ZH_CN,
  resolveLabels,
  CHAT_LABELS_EN,
  CHAT_LABELS_ZH_CN,
  formatAssistantDurationMs,
} from '@bndynet/ichat-messages';
export type {
  ChatPartRenderContext,
  TodoPatchFailureReason,
  TodoPatchResult,
  ChatFormSubmitRequestDetail,
  TodoActionRequestDetail,
  ToolActionRequestDetail,
} from '@bndynet/ichat-messages';
export { ChatInput } from '@bndynet/ichat-input';
export { ChatMessages, ChatPartHost, ChatToolCall, ChatTodo } from '@bndynet/ichat-messages';
